name: Test
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:   [macOS-latest, windows-latest, ubuntu-latest]
        node: [8, 10, 12]
    steps:
      - uses: 'actions/checkout@master'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: ${{ matrix.node }}
      - name: 'Run Tests'
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn run build
          yarn lint

